# Generated by Django 6.0.3 on 2026-03-31 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
